class Constants:
    STYLES_PATH = '../styles/'
    IMAGES_IN_PATH = '../input/images/'
    IMAGES_OUT_PATH = '../results/images/'
    VIDEOS_IN_PATH = '../input/videos/project_video.mp4'
    VIDEOS_OUT_PATH = '../results/videos/'
    DETECTIONS_PATH = '../config/detections.txt'
    VIDEO_DETECTIONS_PATH = '../config/video_detections.txt'
    LOGO_PATH = '../assets/logo.jpg'
    SPINNER_PATH = '../assets/loader.gif'
    ROOT_PATH = '../'
